global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts/*.yml"

scrape_configs:
  - job_name: 'order-service'
    static_configs:
      - targets: ['localhost:8081']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    
  - job_name: 'inventory-service'
    static_configs:
      - targets: ['localhost:8082']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    
  - job_name: 'shipping-service'
    static_configs:
      - targets: ['localhost:8083']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    
  - job_name: 'notification-service'
    static_configs:
      - targets: ['localhost:8084']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    
  - job_name: 'analytics-service'
    static_configs:
      - targets: ['localhost:8085']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s

  - job_name: 'kafka'
    static_configs:
      - targets: ['localhost:9092']
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
