spring:
  application:
    name: integration-tests
    
  datasource:
    # Will be overridden by TestContainers
    url: jdbc:postgresql://localhost:5432/testdb
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    
  kafka:
    # Will be overridden by TestContainers
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: integration-test-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.portfolio.shared.events"

logging:
  level:
    org.testcontainers: INFO
    com.portfolio: DEBUG
    org.springframework.kafka: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Circuit breaker and resilience configuration
resilience4j:
  circuitbreaker:
    instances:
      orderService:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
  retry:
    instances:
      orderService:
        max-attempts: 3
        wait-duration: 1s
        exponential-backoff-multiplier: 2
  timeout:
    instances:
      orderService:
        timeout-duration: 10s