server:
  port: 8085

spring:
  application:
    name: analytics-service
  
  datasource:
    url: jdbc:postgresql://localhost:5436/analyticsdb
    username: analyticsuser
    password: analyticspass123
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: analytics-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.portfolio.shared.events"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.portfolio.analyticsservice: INFO
    org.springframework.kafka: WARN
    
---
spring:
  config:
    activate:
      on-profile: docker
      
  datasource:
    url: jdbc:postgresql://postgres-analytics:5432/analyticsdb
    
  kafka:
    bootstrap-servers: kafka-controller:29092,kafka-broker1:29092,kafka-broker2:29092